### ISSUE TITLE
イベント一覧の日付情報付加

### ISSUE THREAD

**Issue by butchi** [wbawakate/wbawakate.jp#4]
https://github.com/wbawakate/wbawakate.jp/blob/master/src/config/event.yml

```
  date:
    '2017-04-28'
```

のようにイベント開催日の日付を入力（ `23/` から `20/` まで済 ）

**Comment by okku-git** [comment]
追加できる部分は追加しました。
ハッカソン系のイベントが５日間に渡ってたりするので、適当な日付になってます。
